name: Build and Test Publish on Test PyPI

on:
  pull_request:
    branches: [ "stable" ]
  push:
    branches: [ "stable" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-test-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        
    steps:
      - uses: actions/checkout@master
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Create virtual environment
        run: python -m venv airgym-env
          
      - name: Activate virtual environment
        run: |
          source airgym-env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install build and Pypa
        run: python -m pip install build --user
          
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
          
      - name: Publish distribution ðŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
